# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Basket Donation Payments' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Basket Donation Payments
	pod 'Parse'

  target 'Basket Donation PaymentsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Basket Donation PaymentsUITests' do
    # Pods for testing
  end

end
